package org.main.view.booking;

import java.sql.Date;
import java.time.LocalDate;
import java.time.LocalTime;

/**
 * Represents a booking made by staff at the restaurant
 */

public class Booking {
    /**
     * Fields that make up the Booking object
     */
    private Integer id;
    private String dinerFirstName;
    private String dinerSurname;
    private String phoneNo;
    private LocalDate bookingDate;
    private int covers;
    private LocalTime bookingTime;
    private Boolean specialBooking;


    /**
     * Constructor for the Booking class as it is made for the first time
     * @param dinerFirstName
     * @param dinerSurname
     * @param phoneNo
     * @param bookingDate
     * @param covers
     * @param bookingTime
     * @param specialBooking
     */
    public Booking(String dinerFirstName, String dinerSurname, String phoneNo, LocalDate bookingDate, int covers, LocalTime bookingTime, Boolean specialBooking) {
        this.dinerFirstName = dinerFirstName;
        this.dinerSurname = dinerSurname;
        this.phoneNo = phoneNo;
        this.bookingDate = bookingDate;
        this.covers = covers;
        this.bookingTime = bookingTime;
        this.specialBooking = specialBooking;
    }

    /**
     * Constructor for the Booking once a booking ID has been assigned to it by the database
     * The ID is generated by the database, starting at 1 and will auto-increment, value will always be unique
     * @param id
     * @param dinerFirstName
     * @param dinerSurname
     * @param phoneNo
     * @param bookingDate
     * @param covers
     * @param bookingTime
     * @param specialBooking
     */
    public Booking(int id, String dinerFirstName, String dinerSurname, String phoneNo, LocalDate bookingDate, int covers, LocalTime bookingTime, boolean specialBooking) {
        this(dinerFirstName, dinerSurname, phoneNo, bookingDate, covers, bookingTime, specialBooking);
        this.id = id;
    }

    /**
     * Method to return the Booking as a string
     * @return string of all fields in booking, formatted for ease of reading
     */
    @Override
    public String toString(){
        return "Booking \n " +
                "First Name: " + dinerFirstName + "\n" +
                "Surname: " + dinerSurname + "\n" +
                "Phone Number: " + phoneNo + "\n" +
                "Date: " + bookingDate + "\n" +
                "Time: " + bookingTime + "\n" +
                "Covers: " + covers + "\n" +
                "Special: " + (specialBooking ? "Yes" : "No");

    }

    /**
     * @return id (id) as an integer
     * Automatically generated by the database
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id passed in to assign an ID to a booking
     *           ID is generated by the database
     *           Method called in {@link org.main.database.booking.BookingDataAccess}
     */
    public void setId(Integer id) {
        this.id = id;
    }
    /**
     * @return dinerFirstName (Guests First Name) as a String
     */
    public String getDinerFirstName() {
        return dinerFirstName;
    }

    /**
     * @param dinerFirstName passed in to set first name
     */
    public void setDinerFirstName(String dinerFirstName) {
        this.dinerFirstName = dinerFirstName;
    }
    /**
     * @return dinerSurname (Guests Surname) as a String
     */
    public String getDinerSurname() {
        return dinerSurname;
    }
    /**
     * @param dinerSurname passed in to set surname
     */
    public void setDinerSurname(String dinerSurname) {
        this.dinerSurname = dinerSurname;
    }
    /**
     * @return PhoneNo (Phone Number) as a String
     * Using String since phone numbers in the UK start with either '0' or '+'
     */
    public String getPhoneNo() {
        return phoneNo;
    }
    /**
     * @param phoneNo passed in to set phone number
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    /**
     * @return getBookingDate (bookingDate) as type LocalDate {@link LocalDate}
     */
    public LocalDate getBookingDate() {
        return bookingDate;
    }
    /**
     * @param bookingDate passed in to set booking date
     */
    public void setBookingDate(LocalDate bookingDate) {
        this.bookingDate = bookingDate;
    }
    /**
     * @return covers (Number of Guests) as type int
     */
    public int getCovers() {
        return covers;
    }
    /**
     * @param covers passed in to set number of guests
     */
    public void setCovers(int covers) {
        this.covers = covers;
    }
    /**
     * @return getBookingTime as type LocalTime {@link LocalTime}
     */
    public LocalTime getBookingTime() {
        return bookingTime;
    }
    /**
     * @param bookingTime passed in to set booking Time
     */
    public void setBookingTime(LocalTime bookingTime) {
        this.bookingTime = bookingTime;
    }
    /**
     * Special booking is a party of guests of size 12
     * @return getSpecialBooking as type Boolean
     * In terms of the database:
     * 1 = True
     * 0 = False
     */
    public Boolean getSpecialBooking() {
        return specialBooking;
    }
    /**
     * Special booking is a party of guests of size 12
     * @param specialBooking passed in to set boolean value of special booking
     */
    public void setSpecialBooking(Boolean specialBooking) {
        this.specialBooking = specialBooking;
    }
}
